<div class="results-settings">
    <p>Showing:</p>
    <ul class="results-settings__list">
        <li class="results-settings__item current">25</li>
        <li class="results-settings__item"><a href="">50</a></li>
        <li class="results-settings__item"><a href="">100</a></li>
    </ul><!-- end .results-settings__list -->
    <p>of 204 results</p>
</div><!-- end .results-settings -->

<ul class="pagination right-aligned" role="navigation">
    <li class="pagination__item"><a href="" rel="previous">Previous</a></li>
    <li class="pagination__item"><a href="">1</a></li>
    <li class="pagination__item"><a href="">2</a></li>
    <li class="pagination__item current">3</li>
    <li class="pagination__item"><a href="">4</a></li>
    <li class="pagination__item"><a href="">5</a></li>
    <li class="pagination__item">...</li>
    <li class="pagination__item"><a href="">14</a></li>
    <li class="pagination__item"><a href="" rel="next">Next</a></li>
</ul><!-- end .pagination.right-aligned -->