        <div class="global-footer">
			<div class="global-footer__wrapper">
				<ul class="global-footer__links">
					<li class="global-footer__link"><a href="">Helpdesk</a></li>
					<li class="global-footer__link"><a href="">Privacy &amp; Cookies</a></li>
					<li class="global-footer__link">Built by <a href="">Driving Standards Agency</a></li>
				</ul>
				<div class="global-footer__copyright">
					<a href="">&copy; Crown Copyright</a>
				</div>
		    </div><!-- end global-wrapper -->
		</div><!-- end global-footer -->