<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Case details')); ?>

<div class="full-width">

	<!-- Case summary -->
	<div class="case-summary">
		<div class="case-summary__header">
			<h5>Case summary information</h5>
			<a href="" class="case-summary__toggle">Hide</a>
		</div>
		<ul class="case-summary__list">
			<li class="case-summary__item"><b>Case number</b>12341890456</li>
			<li class="case-summary__item"><b>Operator name</b>Super Big Truckers &amp; Ltd.</li>
			<li class="case-summary__item"><b>Licence number</b>OB14256542</li>
			<li class="case-summary__item"><b>ECMS</b>Convictions</li>
			<li class="case-summary__item"><b>Received</b>10/02/2013</li>
			<li class="case-summary__item"><b>Categorie(s)</b>Convictions, another one, another one</li>
			<li class="case-summary__item"><b>Summary</b>Case for convictions against company another really long word</li>
		</ul><!-- end .case-summary__list -->
	</div><!-- end .case-summary -->

	<!-- Horizontal navigation -->
	<ul class="horizontal-navigation" role="navigation" >
		<li class="horizontal-navigation__item"><a href="">Overview</a></li>
		<li class="horizontal-navigation__item current">Convictions</li>
		<li class="horizontal-navigation__item"><a href="">Prohibitions</a></li>
		<li class="horizontal-navigation__item"><a href="">Penalties</a></li>
		<li class="horizontal-navigation__item"><a href="">Statements</a></li>
		<li class="horizontal-navigation__item"><a href="">Complaints</a></li>
		<li class="horizontal-navigation__item"><a href="">Documents</a></li>
		<li class="horizontal-navigation__item"><a href="">Notes</a></li>
	</ul><!-- end .horizontal-navigation -->


</div><!-- end .full-width -->


<div class="full-width">
	<form>
		<div class="table__header">
			<h3>CRUD table</h3>
			<!-- Tables should be wrapped in a <div clas=".table__wrapper">... 
				 element to allow them to overflow correctly  -->
			<div class="actions-container">
				<input class="action--primary" type="submit" value="Add">
				<input class="action--secondary" type="submit" value="Edit">
				<input class="action--warning" type="submit" value="Delete">
			</div><!-- end .actions-container -->
		</div><!-- end .table__header -->

		<div class="table__wrapper">
			<table>
				<thead>
					<tr>
						<th></th>
						<th>Licence no.</th>
						<th>Postcode</th>
						<th>First name</th>
						<th>Last name</th>
						<th>D.O.B</th>
						<th>Conv.</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><input name="row" type="radio"></td>
						<td><a href="">76163222712</a></td>
						<td>LS7 4QP</td>
						<td>James</td>
						<td>Jefferey</td>
						<td>07/02/1963</td>
						<td>14</td>
					</tr>
					<tr>
						<td><input name="row" type="radio"></td>
						<td><a href="">36233242279</a></td>
						<td>LS3 2PS</td>
						<td>Mohammed</td>
						<td>Ali</td>
						<td>23/11/1943</td>
						<td>5</td>
					</tr>
					<tr>
						<td><input name="row" type="radio"></td>
						<td><a href="">86173252712</a></td>
						<td>LS7 4QP</td>
						<td>James</td>
						<td>Jefferey</td>
						<td>07/02/1963</td>
						<td>14</td>
					</tr>
					<tr>
						<td><input name="row" type="radio"></td>
						<td><a href="">8272632422</a></td>
						<td>LS3 2PS</td>
						<td>Mohammed</td>
						<td>Ali</td>
						<td>23/11/1943</td>
						<td>5</td>
					</tr>
				</tbody>
				<tfoot>
					<tr>
						<th colspan="6">Totals</th>
						<td>477</td>
					</tr>
				</tfoot>
			</table>
		</div><!-- end .table__wrapper -->
	</form>
</div>

