<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Case details')); ?>

<div class="full-width">

	<!-- Case summary -->
	<div class="case-summary">
		<div class="case-summary__header">
			<h5>Case summary information</h5>
			<a href="" class="right-aligned">Edit</a>
		</div>
		<ul class="case-summary__list">
			<li class="summary__item"><b>Case number</b>12341890456</li>
			<li class="summary__item"><b>Operator name</b>Super Big Truckers &amp; Ltd.</li>
			<li class="summary__item"><b>Licence number</b>OB14256542</li>
			<li class="summary__item"><b>ECMS</b>Convictions</li>
			<li class="summary__item"><b>Received</b>10/02/2013</li>
			<li class="summary__item"><b>Categorie(s)</b>Convictions, another one, another one</li>
			<li class="summary__item"><b>Summary</b>Case for convictions against company another really long word</li>
		</ul><!-- end .case-summary__list -->
	</div><!-- end .case-summary -->

	<!-- Notices-->
	<div class="notice-container">	
		<div class="notice--warning">
			<p><b>Stay granted pending appeal: </b>UT 12-04-2014</p>
		</div>
		<div class="notice--warning">
			<p><b>Stay refused pending appeal: </b>TC/TR 14-04-2014</p>
		</div>
		<div class="notice--warning">
			<p><b>Appeal in progress: </b>12-04-2014</p>
		</div>
	</div><!-- end .notice-container -->

	<!-- Horizontal navigation -->
	<ul class="horizontal-navigation" role="navigation" >
		<li class="horizontal-navigation__item"><a href="">Overview</a></li>
		<li class="horizontal-navigation__item current">Convictions</li>
		<li class="horizontal-navigation__item"><a href="">Prohibitions</a></li>
		<li class="horizontal-navigation__item"><a href="">Penalties</a></li>
		<li class="horizontal-navigation__item"><a href="">Statements</a></li>
		<li class="horizontal-navigation__item"><a href="">Complaints</a></li>
		<li class="horizontal-navigation__item"><a href="">Documents</a></li>
		<li class="horizontal-navigation__item"><a href="">Notes</a></li>
	</ul><!-- end .horizontal-navigation -->


</div><!-- end .full-width -->


<div class="full-width">

	<!-- Summary -->
	<h3>Summary</h3>
	<div class="summary">
		<ul class="summary__list">
			<li class="summary__item"><b>Case number</b>12341890456</li>
			<li class="summary__item"><b>Operator name</b>Super Big Truckers &amp; Ltd.</li>
			<li class="summary__item"><b>Licence number</b>OB14256542</li>
			<li class="summary__item"><b>ECMS</b>Convictions</li>
			<li class="summary__item"><b>Received</b>10/02/2013</li>
			<li class="summary__item"><b>Categorie(s)</b>Convictions, another one, another one</li>
			<li class="summary__item"><b>Summary</b>Case for convictions against company another really long word</li>
		</ul><!-- end .summary__list -->
	</div><!-- end .summary -->

	<form>
		<div class="table__header">
			<h3>CRUD table</h3>
			<div class="actions-container">
				<input class="action--primary" type="submit" value="Add">
				<input class="action--secondary" type="submit" value="Edit">
				<input class="action--warning" type="submit" value="Delete">
			</div><!-- end .actions-container -->
		</div><!-- end .table__header -->

		<div class="table__wrapper">
			<table>
				<thead>
					<tr>
						<th></th>
						<th>Licence no.</th>
						<th>Postcode</th>
						<th>First name</th>
						<th>Last name</th>
						<th>D.O.B</th>
						<th>Conv.</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><input name="row" type="radio"></td>
						<td><a href="">76163222712</a></td>
						<td>LS7 4QP</td>
						<td>James</td>
						<td>Jefferey</td>
						<td>07/02/1963</td>
						<td>14</td>
					</tr>
					<tr>
						<td><input name="row" type="radio"></td>
						<td><a href="">36233242279</a></td>
						<td>LS3 2PS</td>
						<td>Mohammed</td>
						<td>Ali</td>
						<td>23/11/1943</td>
						<td>5</td>
					</tr>
					<tr>
						<td><input name="row" type="radio"></td>
						<td><a href="">86173252712</a></td>
						<td>LS7 4QP</td>
						<td>James</td>
						<td>Jefferey</td>
						<td>07/02/1963</td>
						<td>14</td>
					</tr>
					<tr>
						<td><input name="row" type="radio"></td>
						<td><a href="">8272632422</a></td>
						<td>LS3 2PS</td>
						<td>Mohammed</td>
						<td>Ali</td>
						<td>23/11/1943</td>
						<td>5</td>
					</tr>
				</tbody>
			</table>
			<div class="notes-container">
				<div class="note">
					<div class="note__text">
						<p><b>Note:</b> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
					</div>
					<div class="note__meta">
						<p><b>By:</b> Kerry Lane</p>
						<p><b>Created:</b> 13:32 03/03/14</p>
					</div>
				</div><!-- end .note -->
				<div class="note">
					<div class="note__text">
						<p><b>Note:</b> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
					</div>
					<div class="note__meta">
						<p><b>By:</b> Kerry Lane</p>
						<p><b>Created:</b> 13:32 03/03/14</p>
					</div>
					<div class="note__actions">
						<a href="">Edit</a>
						<a href="">Delete</a>
					</div>
				</div><!-- end .note -->
			</div><!-- end .notes-container -->
		</div><!-- end .table__wrapper -->
	</form>

	</div><!-- end .full-width -->




	<div class="three-quarters">

		<!-- Submission actions -->
		<h3>Submission actions</h3>	
		<ul class="submission-actions">

			<li class="submission-actions__item">
				<h3>Recommendation: Revoke licence</h3>
				<p>I recommend that we revoke this operator's licence. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo.</p>
				<ul class="summary__list">
					<li class="summary__item"><b>From</b><a href="">Daniel Karribyson</a></li>
					<li class="summary__item"><b>To</b><a href="">Paul Rooney</a></li>
					<li class="summary__item"><b>Created</b>10:14 12/03/14</li>
					<li class="summary__item"><b>Status</b>Urgent</li>
				</ul><!-- end .summary__list -->
			</li><!-- end .submission-actions__item -->

			<li class="submission-actions__item">
				<h3>Decision: Agree</h3>
				<p>I agree with the recommendation to revoke the operator's licence. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo.</p>
				<ul class="summary__list">
					<li class="summary__item"><b>From</b><a href="">Paul Rooney</a></li>
					<li class="summary__item"><b>To</b><a href="">Daniel Karribyson</a></li>
					<li class="summary__item"><b>Created</b>10:14 12/03/14</li>
					<li class="summary__item"><b>Status</b>Urgent</li>
				</ul><!-- end .summary__list -->
			</li><!-- end .submission-actions__item -->

		</ul><!-- end .submission-actions -->

	</div><!-- end .three-quarters -->
