<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Form elements', 'pageSubTitle'=> 'Includes form wrapper elements, labelling, inputs and actions')); ?>

<div class="one-quarter">
    <?php echo $this->render('partials/vertical-navigation.phtml', array('navItems' => array('Address', 'Personal information', 'About you'))); ?>
</div><!-- end .one-quarter -->

<div class="two-thirds">
   	<form>
   		<div class="validation-summary">
			<h3>There was a problem submitting the form</h3>
			<p>Please try the following:</p>
			<ol class="validation-summary__list">
				<li class="validation-summary__item"><a href="#error1">Enter a town or city</a></li>
				<li class="validation-summary__item"><a href="#error2">Enter a date of birth</a></li>
				<li class="validation-summary__item"><a href="#error3">Enter a biography</a></li>
			</ol><!-- end .validation-summary__list -->
		</div><!-- end .validation-summary -->

		<fieldset class="address">
			<legend>Address</legend>
			<fieldset class="postcode-search">
				<legend>Postcode</legend>
				<div class="field inline">
					<label for="postcode-search" class="visually-hidden">Postcode search</label>
        			<input id="postcode-search" name="postcode" type="text" class="short">
				</div>
				<div class="field inline">
					<input class="action--secondary large" type="submit" value="Find address">
				</div>
			</fieldset>
			<div class="field">
				<label for="street-line-one">Street</label>
    			<input id="street-line-one" name="address" type="text" class="long">
			</div>
			<div class="field">
				<label for="street-line-two" class="visually-hidden">Street line 2</label>
    			<input id="street-line-two" name="address" type="text" class="long">
			</div>
			<div class="field">
				<label for="street-line-three" class="visually-hidden">Street line 3</label>
    			<input id="street-line-three" name="address" type="text" class="long">
			</div>
			<div class="field">
				<label for="street-line-four" class="visually-hidden">Street line 4</label>
    			<input id="street-line-four" name="address" type="text" class="long">
			</div>
			<div class="validation-wrapper">
				<ul>
					<li id="error2">Please complete your biography</li>
				</ul>
				<div class="field">
					<label for="town-city">Town/city</label>
	    			<input id="town-city" name="town-city" type="text" class="long">
				</div>
			</div>
		</fieldset><!-- end #address -->

		<fieldset id="personal-information">
			<legend>Personal information (if applicable)</legend>
			<div class="field">
				<label for="title">Title</label>
				<select id="title" name="title">
					<option value="Please select">Mr.</option>
				</select>
			</div>
			<div class="field">
				<label for="first-name">First name (if applicable)</label>
    			<input id="first-name" name="name" class="long">
    			<p class="hint">This is your first christian name</p>
			</div>
			<div class="field">
				<label for="last-name">Last name</label>
    			<input id="last-name" name="name" type="text" class="long" />
			</div>
			<div class="field">
				<label>Date of birth</label>
				<select id="day" name="date-of-birth">
					<option value="Day">Day</option>
				</select>
				<select id="month" name="date-of-birth">
					<option value="Month">Month</option>
				</select>
				<select id="year" name="date-of-birth">
					<option value="Year">Year</option>
				</select>
			</div>
			<fieldset>
				<legend class="legend">Gender</legend>
				<div class="field inline">
					<label><input type="radio" name="gender" checked>Male</label>
				</div>
				<div class="field inline">
					<label><input type="radio" name="gender">Female</label>
				</div>
			</fieldset>
		</fieldset><!-- end #personal-information -->

		<fieldset id="about-you">
			<legend>About you</legend>
			<fieldset>
				<legend>I am interested in</legend>
				<div class="field--list">
					<label for="jobs"><input type="checkbox" id="jobs">Job offers</label>
				</div>
				<div class="field--list">
					<label for="networking"><input type="checkbox" id="networking">Networking</label>
				</div>
				<div class="field--list">
					<label for="business"><input type="checkbox" id="business">Business opportunities</label>
				</div>
			</fieldset>
		</fieldset><!-- end #about-you -->

		<fieldset id="additional-information" class="highlight-box">
			<legend>Additional information</legend>
			<div class="field">
				<p class="hint">Please provide additional information relating to any prior insolvency proceedings. You may also upload evidence such as legal documents.</p>
				<label for="additional-information" class="visually-hidden">Additional information</label>
				<textarea id="additional-information" class="extra-long" placeholder="Enter text here"></textarea>
			</div>
		</fieldset>

		<fieldset id="confirmation">
			<fieldset>
				<legend>Confirm</legend>
				<div class="field--list">
					<label for="confirm"><input type="checkbox" id="confirm">Please tick to confirm that you are aware that you must tell the traffic commissioner immediately of any insolvency proceedings that occur between the submission of your application and a decision being made on the application</label>
				</div>
			</fieldset>
		</fieldset><!-- end #confirmation -->

		<fieldset id="file-uploader">
			
		</fieldset><!-- end #file-uploader -->

		<h3>Summary</h3>
		<div class="read-only">
		    <h2>1. Type of licence</h2>
		    <fieldset>
		        <legend>Operator details</legend>
		        <div class="field">
		            <fieldset>
		                <legend>Where do you operate from?</legend>
		                <label>
		                    <input type="radio" name="operator_location[operator_location]" id="operator_location" placeholder="" value="uk" checked disabled="disabled" checked>Great Britain
		                </label>
		                <label>
		                    <input type="radio" name="operator_location[operator_location]" placeholder="" value="ni" disabled="disabled">Northern Ireland
		                </label>
		            </fieldset>
		        </div>
		    </fieldset>
		    <fieldset>
		        <div class="field">
		            <fieldset>
		                <legend>What type of operator are you?</legend>
		                <label>
		                    <input type="radio" name="operator-type[operator-type]" id="operator-type" placeholder="" value="goods" disabled="disabled">Goods
		                </label>
		                <label>
		                    <input type="radio" name="operator-type[operator-type]" placeholder="" value="psv" checked disabled="disabled" checked>PSV
		                </label>
		            </fieldset>
		        </div>
		    </fieldset>
		    <fieldset>
		        <legend>Licence type</legend>
		        <div class="field">
		            <fieldset>
		                <legend>What type of license do you want to apply for?</legend>
		                <label>
		                    <input type="radio" name="licence-type[licence_type]" id="licence_type" placeholder="" value="restricted" checked disabled="disabled">Restricted</label>
		                <label>
		                    <input type="radio" name="licence-type[licence_type]" placeholder="" value="standard-national" disabled="disabled">Standard National
		                </label>
		                <label>
		                    <input type="radio" name="licence-type[licence_type]" placeholder="" value="standard-international" disabled="disabled">Standard International</label>
		            </fieldset>
		        </div>
		    </fieldset>
		    <h2>3. Operating centres</h2>
		    <h3>Operating centre 1</h3>
		    <fieldset class="address">
		        <legend>Address</legend>
		        <div class="field">
		            <input id="address-line-one" name="address" type="text" class="long" value="10 Broadchurch Street" disabled="disabled">
		            <input id="address-line-two" name="address" type="text" class="long" value="Wainsbrook" disabled="disabled">
		            <input id="town-city" name="town-city" type="text" class="long" value="Shepperton-on-Thames" disabled="disabled">
		            <br />
		            <input id="postcode" name="postcode" type="text" class="short" value="TW17 8JX" disabled="disabled">
		            <br />
		            <select id="country" name="country" disabled="disabled">
		                <option value="United Kingdom" selected>United Kingdom</option>
		                <option value="France">France</option>
		            </select>
		            <p class="hint">The traffic area is predefined from your address. More about traffic areas</p>
		        </div>
		    </fieldset>
		    <!-- end #address -->
		    <fieldset>
		        <legend>Vehicles &amp; trailers</legend>
		        <p class="hint">Please enter the total amount of vehicles &amp; trailers that you would like to keep at this address</p>
		        <div class="field">
		            <label for="no-of-vehicles">Total number of vehicles</label>
		            <input id="no-of-vehicles" name="no-of-vehicles" type="text" class="short" value="12" disabled="disabled">
		        </div>
		        <div class="field">
		            <label for="no-of-trailers">Total number of trailers</label>
		            <input id="no-of-trailers" name="no-of-trailers" type="text" class="short" value="4" disabled="disabled">
		        </div>
		        <fieldset>
		            <legend>Confirm</legend>
		            <div class="field--list">
		                <label for="confirm">
		                    <input type="checkbox" id="confirm" checked disabled="disabled">Please tick to confirm that you are aware that you must tell the traffic commissioner immediately of any insolvency proceedings that occur between the submission of your application and a decision being made on the application</label>
		            </div>
		        </fieldset>
		    </fieldset>
		    <fieldset>
		        <legend>Advertisements</legend>
		        <fieldset>
		            <legend class="legend">Have you advertised your application for this operating center in your local newspaper?</legend>
		            <div class="field inline">
		                <label><input type="radio" name="advertised" disabled="disabled" checked>Yes</label>
		            </div>
		            <div class="field inline">
		                <label><input type="radio" name="advertised" disabled="disabled">No</label>
		            </div>
		        </fieldset>
		        <div class="field">
		            <label for="newspaper-name">Newspaper name (if applicable)</label>
		            <input id="newspaper-name" name="newspaper-name" type="text" class="long" value="The Shepperton Herald" disabled="disabled">
		        </div>
		        <div class="field">
		            <label>Date advertisement was placed</label>
		            <select id="day" name="date-of-birth" disabled="disabled">
		                <option value="07">07</option>
		            </select>
		            <select id="month" name="date-of-birth" disabled="disabled">
		                <option value="04">04</option>
		            </select>
		            <select id="year" name="date-of-birth" disabled="disabled">
		                <option value="13">13</option>
		            </select>
		        </div>
		        <div class="field">
		            <label for="newspaper-name">Advertisement (if applicable) (optional)</label>
		            <p class="hint">Please upload a copy of the advertisement you placed in your local newspaper in relation to your application.</p>
		            <div class="file">
		                <p>myApplication.PDF</p>
		            </div>
		        </div>
		    </fieldset>
		    <h3>Operating centre 2</h3>
		    <fieldset class="address">
		        <legend>Address</legend>
		        <div class="field">
		            <label for="address-line-one">Street</label>
		            <input id="address-line-one" name="address" type="text" class="long" value="288 Wilbrook Farm" disabled="disabled">
		            <input id="address-line-two" name="address" type="text" class="long" value="Wainsbrook" disabled="disabled">
		            <input id="town-city" name="town-city" type="text" class="long" value="Shepperton-on-Thames" disabled="disabled">
		            <input id="postcode" name="postcode" type="text" class="short" value="TW17 8PZ" disabled="disabled">
		            <br />
		            <select id="country" name="country" disabled="disabled">
		                <option value="United Kingdom" selected>United Kingdom</option>
		                <option value="France">France</option>
		            </select>
		            <br />
		            <select id="traffic-area" name="traffic-area" disabled="disabled">
		                <option value="West Yorkshire" selected>West Yorkshire</option>
		                <option value="Cumbria">Cumbria</option>
		            </select>
		            <p class="hint">The traffic area is predefined from your address. More about traffic areas</p>
		        </div>
		    </fieldset>
		    <!-- end #address -->

		    <fieldset>
		        <legend>Vehicles &amp; trailers</legend>
		        <p class="hint">Please enter the total amount of vehicles &amp; trailers that you would like to keep at this address</p>
		        <div class="field">
		            <label for="no-of-vehicles">Total number of vehicles</label>
		            <input id="no-of-vehicles" name="no-of-vehicles" type="text" class="short" value="12" disabled="disabled">
		        </div>
		        <div class="field">
		            <label for="no-of-trailers">Total number of trailers</label>
		            <input id="no-of-trailers" name="no-of-trailers" type="text" class="short" value="4" disabled="disabled">
		        </div>
		        <fieldset>
		            <legend>Confirm</legend>
		            <div class="field">
		                <label for="confirm">
		                    <input type="checkbox" id="confirm" checked disabled="disabled">Please tick to confirm that you are aware that you must tell the traffic commissioner immediately of any insolvency proceedings that occur between the submission of your application and a decision being made on the application</label>
		            </div>
		        </fieldset>
		    </fieldset>
		    <fieldset>
		        <legend>Advertisements</legend>
		        <fieldset>
		            <legend>Have you advertised your application for this operating center in your local newspaper?</legend>
		            <div class="field inline">
		                <label><input type="radio" name="advertised" checked disabled="disabled">Yes</label>
		            </div>
		            <div class="field inline">
		                <label><input type="radio" name="advertised" disabled="disabled">No</label>
		            </div>
		        </fieldset>
		        <div class="field">
		            <label for="newspaper-name">Newspaper name (if applicable)</label>
		            <input id="newspaper-name" name="newspaper-name" type="text" class="long" value="The Shepperton Herald">
		        </div>
		        <div class="field">
		            <label>Date advertisement was placed</label>
		            <select id="day" name="date-of-birth" disabled="disabled">
		                <option value="07">07</option>
		            </select>
		            <select id="month" name="date-of-birth" disabled="disabled">
		                <option value="04">04</option>
		            </select>
		            <select id="year" name="date-of-birth" disabled="disabled">
		                <option value="13">13</option>
		            </select>
		        </div>
		        <div class="field">
		            <label for="newspaper-name">Advertisement (if applicable) (optional)</label>
		            <p class="hint">Please upload a copy of the advertisement you placed in your local newspaper in relation to your application.</p>
		            <div class="file">
		                <p><b>myApplication.PDF</b>
		                </p>
		            </div>
		        </div>
		    </fieldset>
		    <fieldset>
		        <h3>Authorisation</h3>
		        <p class="hint">Enter the <b>total</b> amount of vehicles & trailers that you want authorised on the licence you are applying for.
		            </>
		            <div class="field">
		                <label for="no-of-vehicles">Total number of vehicles</label>
		                <input id="no-of-vehicles" name="no-of-vehicles" type="text" class="short" value="12" disabled="disabled">
		            </div>
		            <div class="field">
		                <label for="no-of-trailers">Total number of trailers</label>
		                <input id="no-of-trailers" name="no-of-trailers" type="text" class="short" value="4" disabled="disabled">
		            </div>
		    </fieldset>
		</div>

		<div class="actions-container">
			<input class="action--secondary large" type="submit" value="Previous">
			<input class="action--primary large" type="submit" value="Next">
			<input class="action--warning large" type="submit" value="Delete">
			<a class="action--tertiary" href="/">Back to home</a>
		</div><!-- end .actions -->

	</form>

</div><!-- end .two-thirds -->
