<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Form js', 'pageSubTitle'=> 'Includes form wrapper elements, labelling, inputs and actions')); ?>

<div class="one-quarter">
    <?php echo $this->render('partials/vertical-navigation.phtml', array('navItems' => array('Postal address', 'Personal information', 'About you'))); ?>
</div><!-- end .one-quarter -->

<div class="two-thirds">

	<form id="form--sign-up">

		<div class="validation-summary">
			<h3>There was a problem submitting the form</h3>
			<p>Please try the following:</p>
			<ol class="validation-summary__list">
<!-- 			<li class="validation-summary__item"><a href="#error1">Enter a town or city</a></li>
				<li class="validation-summary__item"><a href="#error2">Enter a date of birth</a></li>
				<li class="validation-summary__item"><a href="#error3">Enter a biography</a></li> -->
			</ol><!-- end .validation-summary__list -->
		</div><!-- end .validation-summary -->

		<fieldset id="postal-address">
			<legend>Postal address</legend>
			<div class="field">
				<label for="email">Email address</label>
				<input id="email" name="email" type="email" class="long">
			</div>
			<div class="field">
				<label for="address-line-one">Address line 2</label>
    			<input id="address-line-one" name="address[line-1]" type="text" class="long">
			</div>
			<div class="field">
				<label for="town-city">Town/city</label>
    			<input id="town-city" name="town-city" type="text" class="long">
			</div>
			<div class="field">
				<label for="postcode">Postcode</label>
    			<input id="postcode" type="text" name="postcode" class="short">
			</div>
		</fieldset><!-- end #postal-address -->

		<fieldset id="personal-information">
			<legend>Personal information</legend>
			<div class="field">
				<label for="title">Title</label>
				<select id="title" name="title">
					<option value="Please select">Mr.</option>
				</select>
			</div>
			<div class="field">
				<label for="first-name">First name</label>
    			<input id="first-name" name="name" type="text" class="long">
			</div>
			<div class="field">
				<label for="last-name">Last name</label>
    			<input id="last-name" name="name" type="text" class="long" />
			</div>
			<fieldset>
				<legend class="legend">Gender</legend>
				<div class="field--inline">
					<label><input type="radio" name="gender">Male</label>
				</div>
				<div class="field--inline">
					<label><input type="radio" name="gender">Female</label>
				</div>
			</fieldset>
		</fieldset><!-- end #personal-information -->

		<fieldset id="about-you">
			<legend>About you</legend>
			<fieldset>
				<legend>I am interested in</legend>
				<div class="field--list">
					<label for="jobs"><input type="checkbox" id="jobs">Job offers</label>
				</div>
				<div class="field--list">
					<label for="networking"><input type="checkbox" id="networking">Networking</label>
				</div>
				<div class="field--list">
					<label for="business"><input type="checkbox" id="business">Business opportunities</label>
				</div>
			</fieldset>
		</fieldset><!-- end #about-you -->

		<div class="actions-container">
			<input class="action--secondary large" type="submit" value="Previous">
			<input class="action--primary large" type="submit" value="Next">
			<input class="action--warning large" type="submit" value="Delete">
			<a href="/">Back to home</a>
		</div><!-- end .actions -->

	</form>

</div><!-- end .two-thirds -->
