<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Form elements', 'pageSubTitle'=> 'Includes form wrapper elements, labelling, inputs and actions')); ?>

<div class="one-quarter">
    <?php echo $this->render('partials/vertical-navigation.phtml', array('navItems' => array('Address', 'Personal information', 'About you'))); ?>
</div><!-- end .one-quarter -->

<div class="two-thirds">
   	<form>
   		<div class="validation-summary">
			<h3>There was a problem submitting the form</h3>
			<p>Please try the following:</p>
			<ol class="validation-summary__list">
				<li class="validation-summary__item"><a href="#error1">Enter a town or city</a></li>
				<li class="validation-summary__item"><a href="#error2">Enter a date of birth</a></li>
				<li class="validation-summary__item"><a href="#error3">Enter a biography</a></li>
			</ol><!-- end .validation-summary__list -->
		</div><!-- end .validation-summary -->

		<fieldset class="address">
			<legend>Address</legend>
			<fieldset class="highlight-box">
				<legend>Postcode</legend>
				<div class="field inline">
					<label for="postcode-search" class="visually-hidden">Postcode</label>
        			<input id="postcode-search" name="postcode" type="text" class="short">
				</div>
				<div class="field inline">
					<input class="action--primary" type="submit" value="Find address">
				</div>
			</fieldset>
			<div class="field">
				<label for="address-line-one">Street</label>
    			<input id="address-line-one" name="address" type="text" class="long">
			</div>
			<div class="field">
				<label for="address-line-two" class="visually-hidden">Address line 2</label>
    			<input id="address-line-two" name="address" type="text" class="long">
			</div>
			<div class="field">
				<label for="address-line-three" class="visually-hidden">Address line 3</label>
    			<input id="address-line-three" name="address" type="text" class="long">
			</div>
			<div class="validation-wrapper">
				<ul>
					<li id="error2">Please complete your biography</li>
				</ul>
				<div class="field">
					<label for="town-city">Town/city</label>
	    			<input id="town-city" name="town-city" type="text" class="long">
				</div>
			</div>
		</fieldset><!-- end #address -->

		<fieldset id="personal-information">
			<legend>Personal information (if applicable)</legend>
			<div class="field">
				<label for="title">Title</label>
				<select id="title" name="title">
					<option value="Please select">Mr.</option>
				</select>
			</div>
			<div class="field">
				<label for="first-name">First name (if applicable)</label>
    			<input id="first-name" name="name" type="file" class="long" multiple="multiple">
    			<p class="hint">This is your first christian name</p>
			</div>
			<div class="field">
				<label for="last-name">Last name</label>
    			<input id="last-name" name="name" type="text" class="long" />
			</div>
			<div class="field">
				<label>Date of birth</label>
				<select id="day" name="date-of-birth">
					<option value="Day">Day</option>
				</select>
				<select id="month" name="date-of-birth">
					<option value="Month">Month</option>
				</select>
				<select id="year" name="date-of-birth">
					<option value="Year">Year</option>
				</select>
			</div>
			<fieldset>
				<legend class="legend">Gender</legend>
				<div class="field inline">
					<label><input type="radio" name="gender" checked>Male</label>
				</div>
				<div class="field inline">
					<label><input type="radio" name="gender">Female</label>
				</div>
			</fieldset>
		</fieldset><!-- end #personal-information -->

		<fieldset id="about-you">
			<legend>About you</legend>
			<fieldset>
				<legend>I am interested in</legend>
				<div class="field--list">
					<label for="jobs"><input type="checkbox" id="jobs">Job offers</label>
				</div>
				<div class="field--list">
					<label for="networking"><input type="checkbox" id="networking">Networking</label>
				</div>
				<div class="field--list">
					<label for="business"><input type="checkbox" id="business">Business opportunities</label>
				</div>
			</fieldset>
		</fieldset><!-- end #about-you -->

		<fieldset id="additional-information" class="highlight-box">
			<legend>Additional information</legend>
			<div class="field">
				<p class="hint">Please provide additional information relating to any prior insolvency proceedings. You may also upload evidence such as legal documents.</p>
				<label for="additional-information" class="visually-hidden">Additional information</label>
				<textarea id="additional-information" class="extra-long" placeholder="Enter text here"></textarea>
			</div>
		</fieldset>

		<fieldset id="confirmation">
			<fieldset>
				<legend>Confirm</legend>
				<div class="field--list">
					<label for="confirm"><input type="checkbox" id="confirm">Please tick to confirm that you are aware that you must tell the traffic commissioner immediately of any insolvency proceedings that occur between the submission of your application and a decision being made on the application</label>
				</div>
			</fieldset>
		</fieldset><!-- end #confirmation -->

		<div class="actions-container">
			<input class="action--secondary large" type="submit" value="Previous">
			<input class="action--primary large" type="submit" value="Next">
			<input class="action--warning large" type="submit" value="Delete">
			<a href="/">Back to home</a>
		</div><!-- end .actions -->

	</form>

</div><!-- end .two-thirds -->
