<?php 
	echo $this->render('partials/page-header.phtml', 
	array(
		'pageTitle' => 'Navigation elements', 
		'pageSubTitle'=> 'Includes a standard set of vertical and horizontal navigation mechanisms'
		)
	); 
?>

				<div class="full-width">

					<!-- Application navigation -->

					<h3>Application navigation</h3>
					<ul class="application" role="navigation" >
						<li class="application__item complete"><a href=""><span>Type of licence</span></a></li>
						<li class="application__item complete"><a href=""><span>Your business</span></a></li>
						<li class="application__item complete"><a href=""><span>Operating centres</span></a></li>
						<li class="application__item incomplete"><a href=""><span>Transport managers</span></a></li>
						<li class="application__item current"><span>Vehicles &amp; Safety</span></li>
						<li class="application__item"><a href=""><span>Previous history</span></a></li>
						<li class="application__item"><a href=""><span>Review &amp; Declarations</span></a></li>
						<li class="application__item"><a href=""><span>Payment &amp; Submission</span></a></li>
					</ul><!-- end .progress -->

					<hr /><hr /><!-- hr Shouldn't be used in production -->

					<!-- Horizontal navigation -->

					<h3>Horizontal navigation</h3>
					<ul class="horizontal-navigation" role="navigation">
						<li class="horizontal-navigation__item"><a href="">Overview</a></li>
						<li class="horizontal-navigation__item current">Convictions</li>
						<li class="horizontal-navigation__item"><a href="">Prohibitions</a></li>
						<li class="horizontal-navigation__item"><a href="">Penalties</a></li>
						<li class="horizontal-navigation__item"><a href="">Statements</a></li>
						<li class="horizontal-navigation__item"><a href="">Complaints</a></li>
						<li class="horizontal-navigation__item"><a href="">Documents</a></li>
						<li class="horizontal-navigation__item"><a href="">Notes</a></li>
					</ul>

					<hr /><hr /><!-- hr Shouldn't be used in production -->


					<!-- Mega menu -->

					<?php $internAppItems = array(
						'Summary view', 
						'Type of licence', 
						'Entity type', 
						'Operating centres &amp; auth',
						'Transport managers',
						'Vehicles &amp; safety',
						'Previous history',
						'Undertakings &amp declaration',
						'Payment details',
						'Summary & submission',
						'Oppositions',
						'Publications',
						'Conditions',
						'Fees',
						'App decisions',
						'Documents');
					?>

					<h3>Mega menu</h3>
					<ul class="mega-menu" role="navigation">
					<?php foreach($internAppItems as $item) { ?>
						<?php if ($item == 'Transport managers'){ ?>
						<li class="mega-menu__item current">
							<?php echo $item; ?>
						</li>
						<?php } else { ?>
						<li class="mega-menu__item">
							<a href=""><?php echo $item; ?></a>
						</li>
					<?php } } ?>
					</ul><!-- end .mega-menu -->

				</div><!-- end .full-width -->


				<!-- Vertical navigation-->

				<div class="full-width" style="margin-bottom: .5em;">
					<h3>Vertical navigation</h3>
				</div>
				<div class="one-quarter">

					<h4>In this section</h4>
					<ol class="vertical-navigation" role="navigation">
						<li class="vertical-navigation__item">
							<a href="">1. Subsection one</a>
						</li>
						<li class="vertical-navigation__item current">2. Subsection two</li>
						<li class="vertical-navigation__item">
							<a href="">3. Subsection three</a>
						</li>
						<li class="vertical-navigation__item current">
							<a href="">4. Subsection four</a>	
							<ul>
								<li>Add operating centre</li>
							</ul>
						</li>
					</ol><!-- end .vertical-navigation -->

                </div><!-- end .one-quarter -->


                <!-- Filters-->

				<div class="full-width" style="margin-bottom: .5em;">
					<h3>Filters</h3>
				</div>
				<div class="two-thirds">
					<div class="filters">
						<h4>Filter by:</h4>
						<ul class="filters__list">
							<li class="filters__title">Area</li>
							<li class="filters__item"><a href="">North East</a></li>
							<li class="filters__item"><a href="">North West</a></li>
							<li class="filters__item"><a href="">Yorkshire</a></li>
							<li class="filters__item"><a href="">East Midlands</a></li>
							<li class="filters__item"><a href="">West Midlands</a></li>
							<li class="filters__item">
								<label for="east-of-england"><input type="checkbox" name="area" id="east-of-england">East of England</label>
							</li>
							<li class="filters__item">
								<label for="london"><input type="checkbox" name="area" id="london">London</label>
							</li>
							<li class="filters__item">
								<label for="south-east"><input type="checkbox" name="area" id="south-east">South East</label>
							</li>
						</ul><!-- end .filters__list -->
						<ul class="filters__list">
							<li class="filters__title">Gender</li>
							<li class="filters__item"><a href="">Male</a></li>
							<li class="filters__item"><a href="">Female</a></li>
						</ul><!-- end .filters__list -->
					</div>
                </div><!-- end .one-quarter -->


                <!-- Pagination-->

				<div class="full-width">
					<h3>Pagination</h3>
                    <?php echo $this->render('partials/pagination.phtml'); ?>
				</div><!-- end .full-width -->

				