<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Navigation elements', 'pageSubTitle'=> 'Includes a standard set of vertical and horizontal navigation mechanisms')); ?>


				<!-- Progress navigation -->

				<div class="full-width">
					<h3>Progress navigation</h3>
					<ul class="progress" role="navigation" >
						<li class="progress__item"><a href=""><span>Type of licence</span></a></li>
						<li class="progress__item current"><span>Your business</span></li>
						<li class="progress__item"><a href=""><span>Operating centres</span></a></li>
						<li class="progress__item"><a href=""><span>Transport managers</span></a></li>
						<li class="progress__item"><a href=""><span>Vehicle and safety</span></a></li>
						<li class="progress__item"><a href=""><span>Declaration</span></a></li>
						<li class="progress__item"><a href=""><span>Payment</span></a></li>
					</ul><!-- end .progress -->
				</div><!-- end .full-width -->

	
				<!-- Tabbed navigation -->

				<div class="full-width">
					<h3>Tabbed navigation</h3>
					<ul class="tabs" role="navigation" >
						<li class="tabs__item"><a href="">Item one</a></li>
						<li class="tabs__item current">Item two</li>
						<li class="tabs__item"><a href="">Item three</a></li>
						<li class="tabs__item"><a href="">Item four</a></li>
						<li class="tabs__item"><a href="">Item five</a></li>
						<li class="tabs__item"><a href="">Item six</a></li>
						<li class="tabs__item"><a href="">Item seven</a></li>
					</ul><!-- end .tabs -->
					<div class="tabs__content">
						<p>This is the content, switchable by the tabs</p>
					</div>
				</div><!-- end .full-width -->
				

				<!-- Horizontal-navigation -->

				<div class="full-width">
					<h3>Horizontal navigation</h3>
					<ul class="horizontal-navigation" role="navigation" >
						<li class="horizontal-navigation__item"><a href="">Overview</a></li>
						<li class="horizontal-navigation__item current">Convictions</li>
						<li class="horizontal-navigation__item"><a href="">Prohibitions</a></li>
						<li class="horizontal-navigation__item"><a href="">Penalties</a></li>
						<li class="horizontal-navigation__item"><a href="">Statements</a></li>
						<li class="horizontal-navigation__item"><a href="">Complaints</a></li>
						<li class="horizontal-navigation__item"><a href="">Documents</a></li>
						<li class="horizontal-navigation__item"><a href="">Notes</a></li>
					</ul><!-- end .horizontal-navigation -->
				</div><!-- end .full-width -->


				<!-- Accordion -->

				<div class="full-width">
					<h3>Accordion</h3>
                    <ul class="accordion">
                    	<li class="accordion__item">
                    		<h4><a href="">This is a section title</a></h4>
                    		<p>This is a helpful description about the sections</p>
                    		<a class="accordion__item__action" href="">Edit</a>
                    	</li>
                    	<li class="accordion__item">
                    		<h4><a href="">This is another section title</a></h4>
                    		<p>This is a helpful description about the sections</p>
                    		<a class="accordion__item__action" href="">Edit</a>
                    	</li>                    	
                    	<li class="accordion__item">
                    		<h4><a href="">This is another section title</a></h4>
                    		<p>This is a helpful description about the sections</p>
                    		<a class="accordion__item__action" href="">Edit</a>
                    	</li>
                    </ul><!-- end .accordion -->
				</div><!-- end .full-width -->


				<!-- Vertical navigation-->

				<div class="full-width" style="margin-bottom: .5em;">
					<h3>Vertical navigation</h3>
				</div>
				<div class="one-quarter">
	                <?php echo $this->render('partials/vertical-navigation.phtml', array('navItems' => array('Postal address', 'Personal information', 'About you'))); ?>
                </div><!-- end .one-quarter -->


                <!-- Filters-->

				<div class="full-width" style="margin-bottom: .5em;">
					<h3>Filters</h3>
				</div>
				<div class="two-thirds">
					<div class="filters">
						<h4>Filter by:</h4>
						<ul class="filters__list">
							<li class="filters__title">Area</li>
							<li class="filters__item"><a href="">North East</a></li>
							<li class="filters__item"><a href="">North West</a></li>
							<li class="filters__item"><a href="">Yorkshire</a></li>
							<li class="filters__item"><a href="">East Midlands</a></li>
							<li class="filters__item"><a href="">West Midlands</a></li>
							<li class="filters__item"><input type="checkbox" name="area">East of England</input></li>
							<li class="filters__item"><input type="checkbox" name="area">London</input></li>
							<li class="filters__item"><input type="checkbox" name="area">South East</input></li>
						</ul><!-- end .filters__list -->
						<ul class="filters__list">
							<li class="filters__title">Gender</li>
							<li class="filters__item"><a href="">Male</a></li>
							<li class="filters__item"><a href="">Female</a></li>
						</ul><!-- end .filters__list -->
					</div>
                </div><!-- end .one-quarter -->


                <!-- Pagination-->

				<div class="full-width">
					<h3>Pagination</h3>
                    <?php echo $this->render('partials/pagination.phtml'); ?>
				</div><!-- end .full-width -->

				