<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Notices')); ?>

<div class="full-width">
	
	<!-- Notices -->
	<h3>Notice</h3>
	<div class="notice-container">	
		<div class="notice--success">
			<p><b>Well done!</b> You successfully read <a href="#" class="alert-link">this important alert message</a></p>
		</div>
		<div class="notice--info">
			<p><b>Heads up!</b> This <a href="#" class="alert-link">alert needs your attention</a>, but it's not super important.
		</div>
		<div class="notice--warning">
			<p><b>Warning!</b> Better check yourself, you're not <a href="#">looking too good.</a></p>
		</div>
		<div class="notice--danger">
			<p><b>Oh snap!</b> <a href="#">Change a few things up</a> and try submitting again.</p>
		</div>
	</div><!-- end .notice-container -->

</div><!-- end .full-width -->


<div class="three-quarters">
	
	<!-- Summary styling -->
	<h3>Summary</h3>
	<div class="read-only">
		<h2>1. Type of licence</h2>
		<fieldset>
			<legend>Operator details</legend>
			<div class="field">
				<fieldset>
					<legend>Where do you operate from?</legend>
					<label>
						<input type="radio" name="operator_location[operator_location]" id="operator_location" placeholder="" value="uk" checked disabled="disabled" checked>Great Britain
					</label>
					<label>
						<input type="radio" name="operator_location[operator_location]" placeholder="" value="ni" disabled="disabled">Northern Ireland
					</label>
				</fieldset>
			</div>
		</fieldset>

		<fieldset>
			<legend>Operator details</legend>
			<div class="field">
				<fieldset>
					<legend>What type of operator are you?</legend>
					<label>
						<input type="radio" name="operator-type[operator-type]" id="operator-type" placeholder="" value="goods" disabled="disabled">
						Goods
					</label>
					<label>
						<input type="radio" name="operator-type[operator-type]" placeholder="" value="psv" checked disabled="disabled" checked>
						PSV
					</label>
				</fieldset>
			</div>
		</fieldset>

		<fieldset>
			<legend>Licence type</legend>
			<div class="field">
				<fieldset>
					<legend>What type of licence do you want to apply for?</legend>
					<label>
						<input type="radio" name="licence-type[licence_type]" id="licence_type" placeholder="" value="restricted" checked disabled="disabled">Restricted
					</label>
					<label>
						<input type="radio" name="licence-type[licence_type]" placeholder="" value="standard-national" disabled="disabled">Standard National
					</label>
					<label>
						<input type="radio" name="licence-type[licence_type]" placeholder="" value="standard-international" disabled="disabled">Standard International
					</label>
				</fieldset>
			</div>
		</fieldset>

		<h2>3. Operating centres</h2>

		<h3>Operating centre 1</h3>

		<fieldset class="address">
			<legend>Address</legend>
			<div class="field">
    			<input id="address-line-one" name="address" type="text" class="long" value="10 Broadchurch Street" disabled="disabled">
    			<input id="address-line-two" name="address" type="text" class="long" value="Wainsbrook" disabled="disabled">
    			<input id="town-city" name="town-city" type="text" class="long" value="Shepperton-on-Thames" disabled="disabled"><br />
    			<input id="postcode" name="postcode" type="text" class="short" value="TW17 8JX" disabled="disabled"><br />
				<select id="country" name="country" disabled="disabled">
					<option value="United Kingdom" selected>United Kingdom</option>
					<option value="France">France</option>
				</select>
				<p class="hint">The traffic area is predefined from your address. More about traffic areas</p>
			</div>
		</fieldset><!-- end #address -->

		<fieldset>
			<legend>Vehicles &amp; trailers</legend>
			<p class="hint">Please enter the total amount of vehicles &amp; trailers that you would like to keep at this address</p>
			<div class="field">
				<label for="no-of-vehicles">Total number of vehicles</label>
    			<input id="no-of-vehicles" name="no-of-vehicles" type="text" class="short" value="12" disabled="disabled">
			</div>
			<div class="field">
				<label for="no-of-trailers">Total number of trailers</label>
    			<input id="no-of-trailers" name="no-of-trailers" type="text" class="short" value="4" disabled="disabled" >
			</div>
			<fieldset>
				<legend>Confirm</legend>
				<div class="field--list">
					<label for="confirm"><input type="checkbox" id="confirm" checked disabled="disabled">Please tick to confirm that you are aware that you must tell the traffic commissioner immediately of any insolvency proceedings that occur between the submission of your application and a decision being made on the application</label>
				</div>
			</fieldset>
		</fieldset>

		<fieldset>
			<legend>Advertisements</legend>
			<fieldset>
				<legend class="legend">Have you advertised your application for this operating center in your local newspaper?</legend>
				<div class="field inline">
					<label><input type="radio" name="advertised" disabled="disabled" checked>Yes</label>
				</div>
				<div class="field inline">
					<label><input type="radio" name="advertised" disabled="disabled">No</label>
				</div>
			</fieldset>
			<div class="field">
				<label for="newspaper-name">Newspaper name (if applicable)</label>
    			<input id="newspaper-name" name="newspaper-name" type="text" class="long" value="The Shepperton Herald">
			</div>
			<div class="field">
				<label>Date advertisement was placed</label>
				<select id="day" name="date-of-birth" disabled="disabled">
					<option value="07">07</option>
				</select>
				<select id="month" name="date-of-birth" disabled="disabled">
					<option value="04">04</option>
				</select>
				<select id="year" name="date-of-birth" disabled="disabled">
					<option value="13">13</option>
				</select>
			</div>
			<div class="field">
				<label for="newspaper-name">Advertisement (if applicable) (optional)</label>
				<p class="hint">Please upload a copy of the advertisement you placed in your local newspaper in relation to your application.</p>
    			<div class="file">
    				<p><b>myApplication.PDF</b></p>
    			</div>
			</div>
		</fieldset>

		<h3>Operating centre 2</h3>

		<fieldset class="address">
			<legend>Address</legend>
			<div class="field">
				<label for="address-line-one">Street</label>
    			<input id="address-line-one" name="address" type="text" class="long" value="288 Wilbrook Farm" disabled="disabled">
			</div>
			<div class="field">
				<label for="address-line-two" class="visually-hidden">Address line 2</label>
    			<input id="address-line-two" name="address" type="text" class="long" value="Wainsbrook" disabled="disabled">
			</div>
			<div class="field">
				<label for="town-city">Town/city</label>
    			<input id="town-city" name="town-city" type="text" class="long" value="Shepperton-on-Thames" disabled="disabled">
			</div>
			<div class="field">
				<label for="postcode">Postcode</label>
    			<input id="postcode" name="postcode" type="text" class="short" value="TW17 8PZ" disabled="disabled">
			</div>
			<div class="field">
				<label for="country">Country</label>
				<select id="country" name="country" disabled="disabled">
					<option value="United Kingdom" selected>United Kingdom</option>
					<option value="France">France</option>
				</select>
			</div>
			<div class="field">
				<label for="traffic-area">Traffic area</label>
				<select id="traffic-area" name="traffic-area" disabled="disabled">
					<option value="West Yorkshire" selected>West Yorkshire</option>
					<option value="Cumbria">Cumbria</option>
				</select>
				<p class="hint">The traffic area is predefined from your address. More about traffic areas</p>
			</div>
		</fieldset><!-- end #address -->

		<fieldset>
			<legend>Vehicles &amp; trailers</legend>
			<p class="hint">Please enter the total amount of vehicles &amp; trailers that you would like to keep at this address</p>
			<div class="field">
				<label for="no-of-vehicles">Total number of vehicles</label>
    			<input id="no-of-vehicles" name="no-of-vehicles" type="text" class="short" value="12" disabled="disabled">
			</div>
			<div class="field">
				<label for="no-of-trailers">Total number of trailers</label>
    			<input id="no-of-trailers" name="no-of-trailers" type="text" class="short" value="4" disabled="disabled" >
			</div>
			<fieldset>
				<legend>Confirm</legend>
				<div class="field--list">
					<label for="confirm"><input type="checkbox" id="confirm" checked disabled="disabled">Please tick to confirm that you are aware that you must tell the traffic commissioner immediately of any insolvency proceedings that occur between the submission of your application and a decision being made on the application</label>
				</div>
			</fieldset>
		</fieldset>

		<fieldset>
			<legend>Advertisements</legend>
			<fieldset>
				<legend class="legend">Have you advertised your application for this operating center in your local newspaper?</legend>
				<div class="field inline">
					<label><input type="radio" name="advertised" checked disabled="disabled">Yes</label>
				</div>
				<div class="field inline">
					<label><input type="radio" name="advertised" disabled="disabled">No</label>
				</div>
			</fieldset>
			<div class="field">
				<label for="newspaper-name">Newspaper name (if applicable)</label>
    			<input id="newspaper-name" name="newspaper-name" type="text" class="long" value="The Shepperton Herald">
			</div>
			<div class="field">
				<label>Date advertisement was placed</label>
				<select id="day" name="date-of-birth" disabled="disabled">
					<option value="07">07</option>
				</select>
				<select id="month" name="date-of-birth" disabled="disabled">
					<option value="04">04</option>
				</select>
				<select id="year" name="date-of-birth" disabled="disabled">
					<option value="13">13</option>
				</select>
			</div>
			<div class="field">
				<label for="newspaper-name">Advertisement (if applicable) (optional)</label>
				<p class="hint">Please upload a copy of the advertisement you placed in your local newspaper in relation to your application.</p>
    			<div class="file">
    				<p><b>myApplication.PDF</b></p>
    			</div>
			</div>
		</fieldset>

		<fieldset>
			<h3>Authorisation</h3>
			<p class="hint">Enter the <b>total</b> amount of vehicles & trailers that you want authorised on the licence you are applying for.</>
			<div class="field">
				<label for="no-of-vehicles">Total number of vehicles</label>
    			<input id="no-of-vehicles" name="no-of-vehicles" type="text" class="short" value="12" disabled="disabled">
			</div>
			<div class="field">
				<label for="no-of-trailers">Total number of trailers</label>
    			<input id="no-of-trailers" name="no-of-trailers" type="text" class="short" value="4" disabled="disabled" >
			</div>

		</fieldset>

	</div>
	

</div><!-- end .three-quarters -->


