<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Progressive form 1')); ?>

<div class="two-thirds">
	<form> 
		<fieldset id="personal-information">
			<fieldset>
				<legend class="legend">Gender</legend>
				<div class="field--inline">
					<label><input type="radio" name="gender" value="male">Male</label>
				</div>
				<div class="field--inline">
					<label class="radio-female"><input type="radio" name="gender" value="female">Female</label>
				</div>
			</fieldset>
			<div class="field" id="favourite-colour-field">
				<label>What is your favourite colour?</label>
				<select id="favourite-colour" name="favourite-colour">
					<option value="red">Red</option>
					<option value="blue">Blue</option>
					<option value="green">Green</option>
				</select>
			</div>
			<div class="field" id="favourite-month-field">
				<label>What is your favourite month?</label>
				<select id="favourite-month" name="favourite-month">
					<option value="january">January</option>
					<option value="february">February</option>
					<option value="march">March</option>
				</select>
			</div>
		</fieldset><!-- end #personal-information -->

		<div class="actions-container">
			<input class="action--primary large" type="submit" value="Save">
			<a href="">Back to whereever</a>
		</div><!-- end .actions -->

	</form>

</div><!-- end .two-thirds -->

<!-- <script id="inline-js" type="application/json">
	{
		"hiddenFieldsList": [
		    {
		        "fieldName": "gender",
		        "fieldValue": "female",
		        "hiddenElement": "#favourite-colour-field"
		    },
		    {
		        "fieldName": "favourite-colour",
		        "fieldValue": "green",
		        "hiddenElement": "#favourite-month-field"
		    }
		]
	}
</script> -->
