<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Progress form 2', 'pageSubTitle'=> 'An example of a progressive form')); ?>

<div class="two-thirds">
	<form>
		<fieldset>
			<div class="field">
				<label for="first-name">First name</label>
    			<input id="first-name" name="name" type="text" class="long">
			</div>
			<div class="field">
				<label for="last-name">Last name</label>
    			<input id="last-name" name="name" type="text" class="long" />
			</div>
			<div class="field">
				<label for="town">Where were you born?</label>
    			<input id="town" name="town" type="text" class="long" />
			</div>
		</fieldset>

		<div class="actions-container">
			<a href="progressive-form-1" class="action--secondary">Previous</a>
			<a href="progressive-form-3" class="action--primary">Next</a>
		</div><!-- end .actions -->

	</form>

</div><!-- end .two-thirds -->
