<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Progress form 3', 'pageSubTitle'=> 'An example of a progressive form')); ?>

<div class="two-thirds">
	<form>
		<fieldset>
			<div class="field">
				<label for="title">Select option 3</label>
				<select id="title" name="title">
					<option value="">Please select</option>
					<option value="1">First option</option>
					<option value="2">Second option</option>
					<option value="3">Third optio</option>
				</select>
			</div>
		</fieldset>

		<div class="actions-container">
			<a href="progressive-form-2" class="action--secondary">Previous</a>
			<a href="#" class="action--primary">Done</a>
		</div><!-- end .actions -->

	</form>

</div><!-- end .two-thirds -->
