<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Read only', 'pageSubTitle'=> 'A collection of read only elements such as summaries and list items')); ?>

		<div class="two-thirds">
			<div class="summary-box">
				
			</div>	

			<h2>Submission actions</h2>	
			<ul class="submission-actions">
				<li class="submission-action">
					<h3>Recommendation — Revoke licence</h3>
					<p>I recommend that consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus.</p>
					<ul class="submission-action__footer">
						<li class="submission-action__footer__item">
							<b></b>
						</li>
						<li class="submission-action__footer__item"></li>
						<li class="submission-action__footer__item"></li>
						<li class="submission-action__footer__item"></li>
					</ul>
				</li>
			</ul>
				
			</div>		


		</div><!-- end .two-thirds -->


