<?php echo $this->render('partials/page-header.phtml', array('pageTitle' => 'Tables', 'pageSubTitle'=> 'Standard styling for a range of complex tables and surrounding elements')); ?>

		<div class="full-width">

			<!-- CRUD table -->

			<form>
				
				<div class="table__header">
					<h3>CRUD table</h3>
					<!-- Tables should be wrapped in a <div clas=".table__wrapper">... 
						 element to allow them to overflow correctly  -->
					<div class="actions-container">
						<input class="action--primary" type="submit" value="Add">
						<input class="action--secondary" type="submit" value="Edit">
						<input class="action--warning" type="submit" value="Delete">
					</div><!-- end .actions-container -->
				</div><!-- end .table__header -->

				<div class="table__wrapper">
					<table>
						<thead>
							<tr>
								<th></th>
								<th>Licence no.</th>
								<th>Trading name</th>
								<th>Postcode</th>
								<th>First name</th>
								<th>Last name</th>
								<th>D.O.B</th>
								<th>Conv.</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><input name="row" type="radio"></td>
								<td><a href="">76163222712</a></td>
								<td>Jim Jefferey's Haulage LTD</td>
								<td>LS7 4QP</td>
								<td>James</td>
								<td>Jefferey</td>
								<td>07/02/1963</td>
								<td>14</td>
							</tr>
							<tr>
								<td><input name="row" type="radio"></td>
								<td><a href="">36233242279</a></td>
								<td>Amber Taxis</td>
								<td>LS3 2PS</td>
								<td>Mohammed</td>
								<td>Ali</td>
								<td>23/11/1943</td>
								<td>5</td>
							</tr>
							<tr>
								<td><input name="row" type="radio"></td>
								<td><a href="">86173252712</a></td>
								<td>Jim Jefferey's Haulage LTD</td>
								<td>LS7 4QP</td>
								<td>James</td>
								<td>Jefferey</td>
								<td>07/02/1963</td>
								<td>14</td>
							</tr>
							<tr>
								<td><input name="row" type="radio"></td>
								<td><a href="">8272632422</a></td>
								<td>Amber Taxis</td>
								<td>LS3 2PS</td>
								<td>Mohammed</td>
								<td>Ali</td>
								<td>23/11/1943</td>
								<td>5</td>
							</tr>
						</tbody>
						<tfoot>
							<tr>
								<th colspan="7">Totals</th>
								<td>477</td>
							</tr>
						</tfoot>
					</table>
				</div><!-- end .table__wrapper -->
			</form>


			<!-- Read only table -->

			<div class="table__header">
				<h3>Read only table</h3>
			</div><!-- end .table__header -->
			<div class="table__wrapper">
				<table>
					<thead>
						<tr>
							<th>Licence no.</th>
							<th class="sortable selected">Trading name</th>
							<th>Postcode</th>
							<th class="sortable">First name</th>
							<th class="sortable">Last name</th>
							<th>D.O.B</th>
							<th>Conv.</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><a href="">76163222712</a></td>
							<td>Jim Jefferey's Haulage LTD</td>
							<td>LS7 4QP</td>
							<td>James</td>
							<td>Jefferey</td>
							<td>07/02/1963</td>
							<td>14</td>
						</tr>
						<tr>
							<td><a href="">36233242279</a></td>
							<td>Amber Taxis</td>
							<td>LS3 2PS</td>
							<td>Mohammed</td>
							<td>Ali</td>
							<td>23/11/1943</td>
							<td>5</td>
						</tr>
						<tr>
							<td><a href="">86173252712</a></td>
							<td>Jim Jefferey's Haulage LTD</td>
							<td>LS7 4QP</td>
							<td>James</td>
							<td>Jefferey</td>
							<td>07/02/1963</td>
							<td>14</td>
						</tr>
						<tr>
							<td><a href="">8272632422</a></td>
							<td>Amber Taxis</td>
							<td>LS3 2PS</td>
							<td>Mohammed</td>
							<td>Ali</td>
							<td>23/11/1943</td>
							<td>5</td>
						</tr>
					</tbody>
				</table>
			</div><!-- end .table__wrapper -->
			<?php echo $this->render('partials/pagination.phtml'); ?>


			<!-- Multi-action CRUD table -->

			<form>	
				<div class="table__header">
					<h3>Multi-action CRUD table</h3>
					<div class="actions-container">
						<select id="table-actions" name="table-actions">
							<option value="" disabled="disabled" selected>Select actions</option>
							<option value="Add">Add</option>
							<option value="Edit">Edit</option>
							<option value="Delete">Delete</option>
							<option value="Redirect">Redirect</option>
							<option value="Close">Close</option>
						</select>
						<input class="action--secondary" type="submit" value="Submit">
					</div><!-- end .actions-container -->
				</div><!-- end .table__header -->
				<div class="table__wrapper">
					<table>
						<thead>
							<tr>
								<th></th>
								<th>Licence no.</th>
								<th>Trading name</th>
								<th>Postcode</th>
								<th>First name</th>
								<th>Last name</th>
								<th>D.O.B</th>
								<th>Conv.</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><input name="row" type="radio"></td>
								<td><a href="">76163222712</a></td>
								<td>Jim Jefferey's Haulage LTD</td>
								<td>LS7 4QP</td>
								<td>James</td>
								<td>Jefferey</td>
								<td>07/02/1963</td>
								<td>14</td>
							</tr>
							<tr>
								<td><input name="row" type="radio"></td>
								<td><a href="">36233242279</a></td>
								<td>Amber Taxis</td>
								<td>LS3 2PS</td>
								<td>Mohammed</td>
								<td>Ali</td>
								<td>23/11/1943</td>
								<td>5</td>
							</tr>
							<tr>
								<td><input name="row" type="radio"></td>
								<td><a href="">86173252712</a></td>
								<td>Jim Jefferey's Haulage LTD</td>
								<td>LS7 4QP</td>
								<td>James</td>
								<td>Jefferey</td>
								<td>07/02/1963</td>
								<td>14</td>
							</tr>
							<tr>
								<td><input name="row" type="radio"></td>
								<td><a href="">8272632422</a></td>
								<td>Amber Taxis</td>
								<td>LS3 2PS</td>
								<td>Mohammed</td>
								<td>Ali</td>
								<td>23/11/1943</td>
								<td>5</td>
							</tr>
						</tbody>
						<tfoot>
							<tr>
								<th colspan="7">Totals</th>
								<td>477</td>
							</tr>
						</tfoot>
					</table>
				</div><!-- end .table__wrapper -->
			</form>

		</div><!-- end .full-width -->

